"""Релизная миграция

Revision ID: f5d20865c762
Revises: 263d133562ff
Create Date: 2023-09-01 00:02:04.951846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d20865c762'
down_revision: Union[str, None] = '263d133562ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('simple_tasks')
    op.drop_constraint('users_tasks_task_id_fkey', 'users_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'users_tasks', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_tasks', type_='foreignkey')
    op.create_foreign_key('users_tasks_task_id_fkey', 'users_tasks', 'simple_tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_table('simple_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name='simple_tasks_creator_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='simple_tasks_pkey')
    )
    op.drop_table('tasks')
    # ### end Alembic commands ###
